Repository nextcloud/activity, pull requests merged in 2018-04, with the labels that each got.

#257 Skip parameters which are not there instead of failing out
  js/richObjectStringParser.js
Labels: 3. to review, backport-request, bug, feature: stream

#262 Don't update personal settings for admins
  js/settings.js
  templates/settings/admin.php
Labels: 3. to review, bug, feature: settings

#265 [stable13] Skip parameters which are not there instead of failing out
  js/richObjectStringParser.js
Labels: 3. to review
