Repository nextcloud/activity, pull requests merged in 2018-10, with the labels that each got.

#299 Make the object information available on emails
  appinfo/info.xml
  lib/Data.php
  lib/MailQueueHandler.php
  lib/Migration/Version2008Date20181011095117.php
Labels: 3. to review, enhancement, feature: email

#302 remove unneeded -ms-filter (was only needed for IE8)
  css/style.css
Labels: 2. developing, technical debt

#304 use the query builder and cast the values
  lib/MailQueueHandler.php
Labels: 3. to review, bug, feature: email

#305 Add icon to files sidebar tab
  js/activitytabview.js
Labels: 3. to review, design
