Repository nextcloud/activity, pull requests merged in 2018-02, with the labels that each got.

#245 Move transifex config for updated l10n script
  .tx/config
Labels: 3. to review, enhancement

#246 Also send file emails in ASAP mode
  lib/FilesHooks.php
Labels: 3. to review, backport-request, bug, feature: email

#249 [stable13] Also send file emails in ASAP mode
  lib/FilesHooks.php
Labels: 3. to review, bug, feature: email

#250 Update calls for phpunit 6.5
  appinfo/info.xml
  lib/AppInfo/Application.php
  lib/Controller/Settings.php
  lib/Settings/AdminSection.php
  lib/Settings/Personal.php
  lib/Settings/PersonalSection.php
  personal.php
  tests/DataTest.php
  tests/HooksDeleteUserTest.php
  tests/PersonalTest.php
  tests/bootstrap.php
Labels: 3. to review, bug

#248 Make linkable items clickable in HTML emails
  lib/MailQueueHandler.php
  tests/MailQueueHandlerTest.php
Labels: 4. to release, enhancement, feature: email
