Repository nextcloud/activity, pull requests merged in 2018-11, with the labels that each got.

#308 Shorten tab label 'Activities' to 'Activity'
  js/activitytabview.js
Labels: 3. to review, design, enhancement

#310 Add a intermediate migration to fix old installations
  appinfo/info.xml
  lib/Migration/Version2007Date20181107114613.php
Labels: 3. to review, backport-request, bug

#300 Add the mimetype to the preview arrays
  docs/endpoint-v2.md
  lib/Controller/APIv2.php
  tests/Controller/APIv2Test.php
Labels: 3. to review, enhancement, feature: api

#311 Correctly restrict affected users when using command to send emails
  lib/MailQueueHandler.php
Labels: 3. to review, backport-request, bug, feature: email

#315 Use the substract function instead of manual math
  lib/MailQueueHandler.php
Labels: 3. to review, feature: email, technical debt

#312 [stable14] Correctly restrict affected users when using command to send emails
  lib/MailQueueHandler.php
Labels: 3. to review, bug, feature: email

#313 [stable13] Correctly restrict affected users when using command to send emails
  lib/MailQueueHandler.php
Labels: 3. to review, bug, feature: email

#314 Autocomplete for email command
  lib/Command/SendEmails.php
Labels: 3. to review, enhancement, feature: email

#316 Use the full path instead of the file name in HTML emails too
  lib/MailQueueHandler.php
Labels: 3. to review, backport-request, bug, feature: email

#321 Create activity when user unshares a file themselves
  lib/AppInfo/Application.php
  lib/FilesHooks.php
Labels: 3. to review, bug
