Repository nextcloud/activity, pull requests merged in 2019-11, with the labels that each got.

#404 security@nextcloud.com is not being monitored and mails are being dro…
  CONTRIBUTING.md
Labels: 3. to review, technical debt

#395 Don't overwrite user settings on login
  lib/Hooks.php
Labels: enhancement, feature: settings

#406 is_dir can be null on blacklisted files
  lib/ViewInfoCache.php
Labels: 2. developing, backport-request, bug, feature: api, technical debt
