Repository nextcloud/activity, pull requests merged in 2019-02, with the labels that each got.

#343 Unify the HTML encoding handling with other ROS apps
  js/activitytabview.js
  js/richObjectStringParser.js
  js/script.js
Labels: 3. to review, bug

#346 Don't add empty entries to the objects array
  lib/GroupHelper.php
  tests/GroupHelperTest.php
Labels: 3. to review, bug, feature: api

#342 Remove legacy parser
  lib/Controller/APIv1.php
  lib/Controller/Feed.php
  lib/Data.php
  lib/DataHelper.php
  lib/Extension/LegacyParser.php
  lib/Formatter/BaseFormatter.php
  lib/Formatter/CloudIDFormatter.php
  lib/Formatter/FileFormatter.php
  lib/Formatter/IFormatter.php
  lib/Formatter/UserFormatter.php
  lib/GroupHelper.php
  lib/GroupHelperDisabled.php
  lib/MailQueueHandler.php
  lib/Parameter/Collection.php
  lib/Parameter/Factory.php
  lib/Parameter/IParameter.php
  lib/Parameter/Parameter.php
  lib/PlainTextParser.php
  tests/AppInfo/ApplicationTest.php
  tests/Controller/APIv1Test.php
  tests/DataHelperTest.php
  tests/Formatter/BaseFormatterTest.php
  tests/Formatter/CloudIDFormatterTest.php
  tests/Formatter/FileFormatterTest.php
  tests/Formatter/UserFormatterTest.php
  tests/GroupHelperTest.php
  tests/MailQueueHandlerTest.php
  tests/Parameter/CollectionTest.php
  tests/Parameter/FactoryTest.php
  tests/Parameter/ParameterTest.php
  tests/mock/extension.php
  tests/mock/provider.php
  tests/mock/setting1.php
  tests/mock/setting2.php
Labels: 3. to review, technical debt

#349 Ensure parameters are always an array
  lib/GroupHelper.php
Labels: 3. to review, bug

#348 Make sure the parameters are always an array
  lib/GroupHelper.php
  lib/MailQueueHandler.php
Labels: 3. to review, bug, feature: api, feature: email

#351 Only apply .box and .group class styles if they are related to activity
  css/style.scss
Labels: 3. to review, bug
