Repository nextcloud/activity, pull requests merged in 2019-01, with the labels that each got.

#334 Update master php testing versions
  .drone.yml
  .travis.yml
Labels: 4. to release

#336 Move to SCSS and fix app icon for dark theme
  css/settings.scss
  css/style.scss
Labels: 4. to release, backport-request, bug, design

#340 Darktheme invert monochrome icons + Fix handlebars setup
  .drone.yml
  Makefile
  check-handlebars-templates.sh
  compile-handlebars-templates.sh
  js/activitymodel.js
  js/activitytabview.js
  js/script.js
  js/templates.js
  js/templates/activitytabview_activity.handlebars
Labels: 3. to review, bug, feature: sidebar, feature: stream
