Repository nextcloud/activity, pull requests merged in 2019-08, with the labels that each got.

#386 Fix travis database tests
  .travis.yml
Labels: 3. to review

#388 Better dark theme support
  css/style.scss
Labels: 3. to review, backport-request, bug, design, feature: stream

#383 Add expiration event for shares
  lib/FilesHooks.php
Labels: 3. to review, bug
