Repository nextcloud/activity, pull requests merged in 2019-04, with the labels that each got.

#357 Fallback to plaintext subject if no rich subject is set
  lib/MailQueueHandler.php
Labels: 3. to review, backport-request, bug, feature: email

#361 Fix missing translation for "Home folder"
  js/richObjectStringParser.js
  js/templates.js
  js/templates/fileRoot.handlebars
Labels: 3. to review, backport-request, bug, feature: stream

#366 Drop activity_time index
  appinfo/info.xml
  lib/Migration/Version2006Date20170808154933.php
  lib/Migration/Version2007Date20181107114613.php
  lib/Migration/Version2010Date20190416112817.php
Labels: 3. to review, bug
