Repository nextcloud/activity, pull requests merged in 2020-04, with the labels that each got.

#445 catch new notfound exception while trying to get owner
  lib/FilesHooks.php
Labels: backport-request

#190 Use the usermountcache to get all users who have access to a file
  lib/FilesHooks.php
  tests/FilesHooksTest.php
Labels: 3. to review, backport-request, enhancement, feature: api

#448 Skip notifications for users with invalid email address.
  lib/MailQueueHandler.php
  tests/MailQueueHandlerTest.php
Labels: 3. to review, bug

#420 Add Calendar event proper formatting
  js/richObjectStringParser.js
  js/templates.js
  js/templates/calendarEvent.handlebars
Labels: 3. to review
