Repository nextcloud/activity, pull requests merged in 2020-09, with the labels that each got.

#488 fix digest activity count not limiting to own activity correctly.
  lib/DigestSender.php
Labels: 3. to review

#491 Fix activity tab in the files sidebar
  js/activitytabview.js
Labels: 4. to release, bug

#492 Bugfix/noid/email and notifications fixes
  lib/FilesHooks.php
  lib/UserSettings.php
  tests/FilesHooksTest.php
Labels: 3. to review, bug, feature: email, feature: settings, feature: stream

#493 Only respect the favorite setting for users that favorited
  lib/FilesHooks.php
Labels: 3. to review, bug, feature: settings

#490 fix new event documentation
  docs/create.md
Labels: 3. to review, bug, feature: api
