Repository nextcloud/activity, pull requests merged in 2021-03, with the labels that each got.

#561 Fix 'Daily activity summary' email subject translation
  lib/DigestSender.php
Labels: 3. to review, backport-request, bug, feature: email

#564 Fix PHP 7.3 github action
  .github/workflows/phpunit.yml
Labels: 3. to review, bug

#565 Fix notifying own activities
  lib/NotificationGenerator.php
Labels: 3. to review, bug, php

#569 Send the footer with the defined language
  lib/DigestSender.php
  lib/MailQueueHandler.php
Labels: 3. to review, backport-request, feature: email
