Repository nextcloud/activity, pull requests merged in 2021-11, with the labels that each got.

#652 Update version on master
  appinfo/info.xml
Labels: 4. to release

#657 Fix reenabling the email option
  js/admin.js
Labels: bug, 3. to review, backport-request, feature: settings

#663 fix link to activity section
  lib/Navigation.php
Labels: bug, 3. to review, backport-request

#665 Pass activity link to notification
  lib/NotificationGenerator.php
Labels: bug, 3. to review

#653 Update npm and node engines versions
  package.json
Labels: dependencies

#668 [stable23] Pass activity link to notification
  lib/NotificationGenerator.php
Labels: bug, 3. to review

#667 [stable22] Pass activity link to notification
  lib/NotificationGenerator.php
Labels: bug, 3. to review

#666 [stable21] Pass activity link to notification
  lib/NotificationGenerator.php
Labels: bug, 3. to review
