Repository nextcloud/activity, pull requests merged in 2021-04, with the labels that each got.

#572 Remove self setting checking which can not be set anymore
  lib/Consumer.php
  lib/Data.php
  lib/FilesHooks.php
  lib/Settings/Admin.php
  lib/Settings/Personal.php
  tests/ConsumerTest.php
  tests/FilesHooksTest.php
  tests/UserSettingsTest.php
Labels: 3. to review, bug, feature: email, feature: stream

#576 Ensure link names are unique for accessibility, thanks @nickvergessen, fix #575
  js/script.js
  lib/Controller/APIv2Controller.php
  tests/Controller/APIv2ControllerTest.php
Labels: 4. to release, backport-request, bug, design, feature: stream

#577 Remove unneeded service replacements
  tests/Controller/APIv2ControllerTest.php
  tests/Controller/ActivitiesControllerTest.php
  tests/DataTest.php
Labels: 3. to review, technical debt
