Repository nextcloud/activity, pull requests merged in 2021-07, with the labels that each got.

#600 Fix preference name when generating notifications
  lib/NotificationGenerator.php
Labels: 3. to review, backport-request, bug, feature: settings

#604 Fix monochrome icon detection for correct dark mode invert
  js/script.js
Labels: 3. to review, backport-request, bug, feature: stream

#598 Dashboard widget: Activity by others
  .gitattributes
  Makefile
  composer.lock
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  lib/AppInfo/Application.php
  lib/Dashboard/ActivityWidget.php
  package-lock.json
  package.json
  src/dashboard.js
  src/views/Dashboard.vue
  webpack.js
Labels: 3. to review, enhancement, integration

#609 Fix "Enable notification emails"
  js/admin.js
Labels: 3. to review, backport-request, bug, feature: settings

#610 show add, del and restored files within by and self filter
  lib/UserSettings.php
Labels: 3. to review, bug

#617 Only call getCloudId if needed
  lib/FilesHooks.php
Labels: 3. to review, backport-request, bug

#619 Fix translation syncing
  .l10nignore
Labels: 3. to review, bug, high

#546 Don't break sending emails with non-string parameters
  lib/DigestSender.php
  lib/MailQueueHandler.php
Labels: 3. to review, bug, feature: email

#621 link from app-navigation-settings to personal settings
  css/style.scss
  lib/Navigation.php
  templates/stream.app.navigation.php
  tests/Controller/ActivitiesControllerTest.php
Labels: 3. to review, design, enhancement
