Repository nextcloud/activity, pull requests merged in 2022-04, with the labels that each got.

#779 Fallback to the admin settings if the user did not configure it
  lib/Settings/Admin.php
  lib/UserSettings.php
  templates/settings/admin.php
  tests/UserSettingsTest.php
Labels: enhancement, 3. to review, backport-request, feature: settings

#744 Request preview with the same size as in the file listing
  lib/Controller/APIv2Controller.php
  tests/Controller/APIv2ControllerTest.php
Labels: 2. developing

#768 Replace deprecated String.prototype.substr()
  cypress/utils/index.js
Labels: 3. to review, feature: stream

#797 Adapt cypress tests to new login elements
  cypress/support/commands.js
Labels: bug, 3. to review, integration
