Repository nextcloud/activity, pull requests merged in 2022-08, with the labels that each got.

#859 Fix monochrome invert rule
  css/style.css
Labels: bug, 3. to review, feature: stream

#862 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#871 Simplify the preview information
  composer.lock
  lib/Controller/APIv2Controller.php
  lib/ViewInfoCache.php
  psalm.xml
  tests/Controller/APIv2ControllerTest.php
  tests/FilesHooksTest.php
  tests/ViewInfoCacheTest.php
  tests/stubs/oc_hooks_emitter.php
Labels: enhancement, 4. to release, feature: api

#873 Fix submit buttons in cypress tests
  cypress/support/commands.js
Labels: bug, 3. to review

#866 Update npm and node engines versions
  package.json
Labels: dependencies

#883 [stable24] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#884 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#881 [stable22] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 4. to release, dependencies

#882 [stable23] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#888 Fix translation ignore
  .l10nignore
Labels: bug, 3. to review

#895 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#896 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#900 Fix broken select/label ID/name mismatch
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/components/EmailSettings.vue
Labels: bug, 3. to review, feature: settings

#899 Add role=navigation and aria-current
  js/script.js
  templates/stream.app.navigation.php
Labels: bug, 3. to review, feature: stream, accessibility
