Repository nextcloud/activity, pull requests merged in 2022-11, with the labels that each got.

#993 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#994 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#999 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1000 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1001 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#927 Rename user to people
  README.md
  appinfo/info.xml
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  package.json
  src/views/DefaultActivitySettings.vue
Labels: 3. to review

#1003 [stable25] Run NPM audit fix
  package-lock.json
Labels: bug, 3. to review

#1018 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
