Repository nextcloud/activity, pull requests merged in 2022-07, with the labels that each got.

#841 [Documentation] Clarify usage of Activity filters
  docs/endpoint-v2.md
Labels: bug, 3. to review, feature: api, php

#850 Fix contrast issue for add icon
  img/add-color.svg
Labels: bug, design, 3. to review

#853 Rename settings to activity settings on bottom left
  templates/stream.app.navigation.php
Labels: 3. to review, accessibility

#857 Rename fileList selector
  cypress/support/commands.js
Labels: 2. developing
