Repository nextcloud/activity, pull requests merged in 2022-01, with the labels that each got.

#650 Add rebase command from organization workflow template
  .github/workflows/command-rebase.yml
Labels: 3. to review

#674 Change base image for cypress' docker image
  cypress/Dockerfile
Labels: bug, 4. to release

#673 Add dependabot to auto update js and php deps
  .github/dependabot.yml
Labels: 4. to release, dependencies

#690 Create command-compile.yml
  .github/workflows/command-compile.yml
Labels: enhancement, 3. to review

#697 Add auto-approve workflow for deps update PRs
  .github/workflows/dependabot-approve-merge.yml
Labels: 3. to review, dependencies

#702 Update php lint workflows
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint.yml
Labels: 3. to review, technical debt

#705 Create block-merge-freeze.yml
  .github/workflows/block-merge-freeze.yml
Labels: backport-request

#714 Update master php testing versions
  .github/workflows/lint-php.yml
  .github/workflows/phpunit.yml
  lib/Controller/APIv2Controller.php
Labels: 3. to review, backport-request
