Repository nextcloud/activity, pull requests merged in 2022-09, with the labels that each got.

#909 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#916 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#917 [stable22] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#920 Fix icon color in dark mode
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  src/views/Dashboard.vue
Labels: bug, 3. to review

#926 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#912 Implement new dashboard API
  lib/Dashboard/ActivityWidget.php
Labels: enhancement, 3. to review, php

#934 [stable25] Update christophwurst/nextcloud dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#933 [stable23] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#931 [stable24] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies

#932 [master] Update christophwurst/nextcloud dependency
  composer.lock
Labels: 3. to review, dependencies
