Repository nextcloud/activity, pull requests merged in 2022-10, with the labels that each got.

#944 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#943 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#942 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#941 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#949 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#948 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#950 [stable25] Migrate to @nextcloud/vue-richtext
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
  package.json
  src/components/Activity.vue
  src/tests/__snapshots__/Activity.test.js.snap
Labels: bug, 3. to review

#951 Remove old JS tests from before Vue times that don't install anymore
  tests/js/activitycollectionSpec.js
  tests/js/activitytabviewSpec.js
  tests/js/karma.config.js
  tests/js/package.json
  tests/js/scriptSpec.js
Labels: bug, 3. to review

#952 Do not pass an instance of User where a string is expected
  lib/MailQueueHandler.php
Labels: 3. to review, backport-request

#967 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: backport-request, dependencies

#971 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#970 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#965 Updating phpunit-oci.yml workflow from template
  .github/workflows/phpunit-oci.yml
Labels: dependencies

#968 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#969 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#966 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#964 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#963 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#972 [stable24] Run NPM audit fix
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
Labels: bug, 3. to review

#973 [stable23] Run NPM audit fix
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
Labels: bug, 3. to review

#979 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#978 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#991 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#990 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#989 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
