Repository nextcloud/activity, pull requests merged in 2022-12, with the labels that each got.

#1021 [stable23] Do not pass an instance of User where a string is expected
  lib/MailQueueHandler.php
Labels: bug, 3. to review

#1022 Revert "[stable23] Do not pass an instance of User where a string is expected"
  lib/MailQueueHandler.php
Labels: 4. to release

#1025 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1023 Revert "Revert "[stable23] Do not pass an instance of User where a string is expected""
  lib/MailQueueHandler.php
Labels: 3. to review

#1029 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1033 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1034 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1040 [stable23] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1039 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
