Repository nextcloud/activity, pull requests merged in 2022-06, with the labels that each got.

#815 Limit the $limit to a maximum of 200
  lib/Data.php
Labels: bug, 3. to review, backport-request

#821 Enable keyboard navigation to user label and avatar
  css/style.scss
  js/templates.js
  js/templates/userLocal.handlebars
Labels: 3. to review

#827 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#826 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#832 Improve email logging
  lib/MailQueueHandler.php
Labels: bug, 3. to review
