Repository nextcloud/activity, pull requests merged in 2022-03, with the labels that each got.

#749 Don't query user settings unnecessarily
  lib/UserSettings.php
Labels: 3. to review, feature: api, feature: settings, technical debt

#756 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#755 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#754 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#730 [stable22] Make background job time insensitive
  lib/BackgroundJob/ExpireActivities.php
  tests/AppInfo/ApplicationTest.php
  tests/BackgroundJob/ExpireActivitiesTest.php
  tests/DataDeleteActivitiesTest.php
Labels: enhancement, 4. to release, technical debt

#759 l10n: Change to lowercase
  templates/stream.app.navigation.php
Labels: enhancement, 3. to review

#761 [stable23] change link name
  templates/stream.app.navigation.php
Labels: enhancement, 3. to review
