Repository nextcloud/activity, pull requests merged in 2022-05, with the labels that each got.

#796 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#803 Add filter invert for monochrome icons
  css/style.scss
Labels: bug, design, 3. to review

#804 Updating command-rebase.yml workflow from template
  .github/workflows/command-rebase.yml
Labels: dependencies

#812 Save parameters also in the notifications
  lib/NotificationGenerator.php
Labels: bug, 3. to review, backport-request
