Repository nextcloud/activity, pull requests merged in 2023-01, with the labels that each got.

#1049 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1050 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1052 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1051 Replace custom tooltips with native tooltips
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  js/feedSettings.js
  js/script.js
  js/templates.js
  js/templates/file.handlebars
  js/templates/fileRoot.handlebars
  package.json
  src/components/Activity.vue
  src/components/richArgumentsTypes/FileRichArgument.vue
  src/tests/__snapshots__/Activity.test.js.snap
Labels: 4. to release, backport-request

#1053 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1063 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1069 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1068 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1067 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1065 Show full date after headings like "Today" as a hidden-visually span
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  js/script.js
  src/components/Activity.vue
  src/tests/__snapshots__/Activity.test.js.snap
Labels: 3. to review, backport-request
