Repository nextcloud/activity, pull requests merged in 2023-05, with the labels that each got.

#1154 Use SVG icon for the sidebar tab
  js/activity-node_modules_nextcloud_auth_dist_index_esm_js-src_views_ActivityTab_vue.js
  js/activity-node_modules_nextcloud_auth_dist_index_esm_js-src_views_ActivityTab_vue.js.map
  js/activity-node_modules_nextcloud_axios_dist_index_esm_js-node_modules_nextcloud_capabilities_dist_index-0e7ea0.js
  js/activity-node_modules_nextcloud_axios_dist_index_esm_js-node_modules_nextcloud_capabilities_dist_index-0e7ea0.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
  package.json
  src/sidebar.js
  webpack.js
Labels: bug, 4. to release, feature: sidebar, javascript

#1160 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1159 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1161 Bump @nextcloud/vue to 7.11.3
  js/activity-323.js
  js/activity-323.js.LICENSE.txt
  js/activity-323.js.map
  js/activity-783.js
  js/activity-783.js.LICENSE.txt
  js/activity-783.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
  package.json
  src/tests/__snapshots__/Activity.test.js.snap
Labels: 3. to review

#1165 Adapt test to modern getMount()
  lib/FilesHooks.php
  tests/FilesHooksTest.php
Labels: bug, 3. to review, technical debt

#1145 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1171 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1166 Use the color-primary-element* variables
  css/style.css
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/components/Checkbox.vue
Labels: bug, design, 3. to review

#1172 Add npm audit workflow
  .github/workflows/npm-audit-fix.yml
Labels: 3. to review, dependencies

#1176 [stable25] Fix npm audit
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1174 [master] Fix npm audit
  js/activity-323.js
  js/activity-323.js.map
  js/activity-783.js
  js/activity-783.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1186 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1188 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1195 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
