Repository nextcloud/activity, pull requests merged in 2023-10, with the labels that each got.

#1347 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1259 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1348 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1314 [stable25] fix(db): also chunk MariaDB deletes
  lib/AppInfo/Application.php
  lib/Data.php
  psalm.xml
  tests/Controller/APIv1ControllerTest.php
  tests/DataDeleteActivitiesTest.php
  tests/DataTest.php
Labels: bug, 3. to review

#1356 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1349 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1352 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1355 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1351 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1354 [master] Fix npm audit
  cypress/e2e/filesUtils.ts
  cypress/e2e/sidebarUtils.ts
  package-lock.json
Labels: 3. to review, dependencies

#1357 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1361 fix(cypress): Make sure cypress tests work with upcoming Nextcloud 28
  cypress.config.ts
  cypress/dockerNode.ts
  cypress/e2e/filesUtils.ts
  cypress/e2e/settings.cy.ts
  cypress/e2e/sidebarUtils.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/views/DailySummary.vue
Labels: bug, 3. to review

#1359 fix: chunk delete in query
  lib/Data.php
Labels: bug, 3. to review, backport-request

#1350 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1363 fix(sidebar): Only load chunk once
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  src/sidebar.js
Labels: bug, 3. to review

#1367 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1341 Remove click functionality on row entry
  cypress/e2e/settings.cy.ts
  js/activity-172.js
  js/activity-172.js.map
  js/activity-292.js
  js/activity-292.js.LICENSE.txt
  js/activity-690.js
  js/activity-690.js.LICENSE.txt
  js/activity-819.js
  js/activity-819.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/components/ActivityGrid.vue
Labels: 3. to review, feedback-requested

#1371 fix(settings): html validation
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/components/ActivityGrid.vue
  src/components/Checkbox.vue
Labels: bug, 3. to review, feature: settings, accessibility

#1372 fix: main page html validation
  css/style.css
  js/templates.js
  src/templates/userLocal.handlebars
Labels: bug, 3. to review, accessibility

#1378 Remove `aria-hidden` for table header
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  src/components/ActivityGrid.vue
Labels: 3. to review

#1376 [stable26] Fix npm audit
  js/activity-471.js
  js/activity-471.js.LICENSE.txt
  js/activity-471.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1375 [stable27] Fix npm audit
  js/activity-830.js
  js/activity-830.js.LICENSE.txt
  js/activity-830.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies
