Repository nextcloud/activity, pull requests merged in 2023-03, with the labels that each got.

#1107 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1106 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1081 Create headings for sidebar pages
  js/script.js
  lib/Controller/ActivitiesController.php
  tests/Controller/ActivitiesControllerTest.php
Labels: 3. to review, backport-request

#1119 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1120 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1129 [master] Update nextcloud/ocp dependency
  composer.lock
  tests/Mock/Provider.php
  tests/Mock/Setting1.php
  tests/Mock/Setting2.php
Labels: 3. to review, dependencies

#1123 Use button element and add label to make copy RSS link button accessible
  css/style.css
  templates/stream.app.navigation.php
Labels: 3. to review, backport-request, accessibility

#1128 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1130 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1135 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1127 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
