Repository nextcloud/activity, pull requests merged in 2023-12, with the labels that each got.

#1444 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1446 fix(preferences): Remove unchangable activity preferences
  appinfo/info.xml
  lib/BackgroundJob/RemoveFormerActivitySettings.php
Labels: bug, 3. to review, backport-request, feature: settings

#1450 enh: Add navigation label
  js/activity-app.mjs
  js/activity-app.mjs.map
  src/views/ActivityAppNavigation.vue
Labels: 3. to review, backport-request, accessibility

#1453 Re-enable the move action in cy tests
  cypress/e2e/filesUtils.ts
  cypress/e2e/sidebar.cy.ts
Labels: 3. to review, backport-request, technical debt, javascript

#1459 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1458 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1366 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1436 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1437 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1369 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1465 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1377 [stable25] Fix npm audit
  __mocks__/@nextcloud/axios.js
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested
