Repository nextcloud/activity, pull requests merged in 2023-11, with the labels that each got.

#1368 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1394 fix: Add stub for files event to fix psalm error
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
  psalm.xml
  tests/stubs/oca_files_event.php
Labels: bug, 3. to review, php

#1385 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1395 [stable27] fix: chunk delete in query
  lib/Data.php
Labels: bug, 3. to review, backport-request

#1353 [stable24] Fix npm audit
  .github/workflows/block-merge-eol.yml
  .github/workflows/cypress.yml.txt
  .github/workflows/fixup.yml
  .github/workflows/old-ci.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/phpunit.yml
  composer.json
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
  package.json
Labels: 3. to review, dependencies, feedback-requested

#1400 feat(rss): Add server name to the RSS feed title
  lib/Controller/FeedController.php
  psalm.xml
  templates/rss.php
  tests/Controller/FeedControllerTest.php
  tests/Template/RssTest.php
  tests/stubs/oca_theming_defaults.php
Labels: enhancement, 3. to review

#1404 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1403 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1407 [stable26] Fix npm audit
  __mocks__/@nextcloud/axios.js
  js/activity-139.js
  js/activity-139.js.LICENSE.txt
  js/activity-139.js.map
  js/activity-620.js
  js/activity-620.js.LICENSE.txt
  js/activity-620.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1405 [stable24] Fix npm audit
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
  src/tests/__snapshots__/Activity.test.js.snap
Labels: 3. to review, dependencies

#1426 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1427 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1431 fix(i18n): Fixed typo
  js/activity-app.mjs
  js/activity-app.mjs.map
  src/views/ActivityAppFeed.vue
Labels: bug, 3. to review

#1435 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
