Repository nextcloud/activity, pull requests merged in 2023-02, with the labels that each got.

#1071 Create an unordered list for the list of activities
  css/style.css
  js/script.js
Labels: 3. to review, backport-request

#1077 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1078 [stable25] Create an unordered list for the list of activities
  css/style.css
  js/script.js
Labels: 3. to review

#1079 perf: Lazy load dashboard components
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.LICENSE.txt
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  src/dashboard.js
  webpack.js
Labels: enhancement, 3. to review

#1030 [stable24] groupfolder+acl
  lib/FilesHooks.php
  psalm.xml
Labels: 3. to review

#1031 [stable23] groupfolders+acl
  lib/FilesHooks.php
Labels: 3. to review

#1086 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1088 Update documentation about setRichSubject
  docs/provider.md
Labels: 3. to review

#1099 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1097 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1098 [stable24] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
