Repository nextcloud/activity, pull requests merged in 2023-06, with the labels that each got.

#1200 [stable27] chore: update workflows from templates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/command-rebase.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit-summary-when-unrelated.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review

#1211 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1210 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1212 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1220 chore: update node engines to next LTS
  package.json
Labels: 3. to review, dependencies, automated

#1217 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1223 [stable27] Fix npm audit
  js/activity-323.js
  js/activity-323.js.LICENSE.txt
  js/activity-323.js.map
  js/activity-783.js
  js/activity-783.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.LICENSE.txt
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.LICENSE.txt
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.LICENSE.txt
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1225 [master] Fix npm audit
  js/activity-472.js
  js/activity-472.js.LICENSE.txt
  js/activity-472.js.map
  js/activity-783.js
  js/activity-783.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.LICENSE.txt
  js/activity-adminSettings.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.LICENSE.txt
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.LICENSE.txt
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1222 [stable25] Fix npm audit
  js/activity-adminSettings.js
  js/activity-adminSettings.js.LICENSE.txt
  js/activity-adminSettings.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.LICENSE.txt
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.LICENSE.txt
  js/activity-sidebar.js.map
  package-lock.json
Labels: 3. to review, dependencies

#1218 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1232 Updating cypress.yml workflow from template
  .github/workflows/cypress.yml
Labels: dependencies
