Repository nextcloud/activity, pull requests merged in 2023-07, with the labels that each got.

#1244 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1247 Re-add templates.js
  js/templates.js
  package.json
Labels: bug, 3. to review

#1246 Create pr-feedback.yml
  .github/workflows/pr-feedback.yml
Labels: 3. to review

#1250 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1249 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1243 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1248 [stable25] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1241 [stable25] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1264 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1267 Remove color on hovered and focused link
  css/style.css
Labels: 3. to review
