Repository nextcloud/activity, pull requests merged in 2023-08, with the labels that each got.

#1231 Remove unneeded margin after paragraphs
  js/activity-160.js
  js/activity-160.js.map
  js/activity-499.js
  js/activity-499.js.LICENSE.txt
  js/activity-499.js.map
  js/activity-51.js
  js/activity-51.js.LICENSE.txt
  js/activity-51.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.LICENSE.txt
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  package-lock.json
  package.json
  src/views/Dashboard.vue
Labels: 3. to review

#1295 Fix Cypress tests for F2V
  cypress/e2e/filesUtils.ts
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
Labels: 3. to review, technical debt

#1285 Drop Symfony event dispatcher
  composer.json
  composer.lock
  lib/AppInfo/Application.php
  lib/Capabilities.php
  lib/Controller/ActivitiesController.php
  lib/Event/LoadAdditionalScriptsEvent.php
  lib/FilesHooksStatic.php
  lib/Listener/ShareEventListener.php
  tests/Controller/ActivitiesControllerTest.php
Labels: bug, 3. to review, technical debt, php
