Repository nextcloud/activity, pull requests merged in 2023-09, with the labels that each got.

#1298 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1284 perf(dashboard): implement widget item api v2
  js/activity-499.js
  js/activity-499.js.LICENSE.txt
  js/activity-499.js.map
  js/activity-51.js
  js/activity-51.js.map
  js/activity-568.js
  js/activity-568.js.LICENSE.txt
  js/activity-568.js.map
  js/activity-dashboard-lazy.js
  js/activity-dashboard-lazy.js.LICENSE.txt
  js/activity-dashboard-lazy.js.map
  js/activity-dashboard.js
  js/activity-dashboard.js.LICENSE.txt
  js/activity-dashboard.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  lib/Dashboard/ActivityWidget.php
  package-lock.json
  package.json
  src/dashboard.js
  src/views/Dashboard.vue
  webpack.js
Labels: enhancement, 4. to release

#1303 chore(deps): Move cs-fixer into a composer bin
  .github/dependabot.yml
  .github/workflows/phpunit-oci.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: bug, 3. to review, technical debt, dependencies

#1304 [stable27] Resolve dependency hell
  .github/workflows/phpunit-oci.yml
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  psalm.xml
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: bug, 3. to review, dependencies

#1301 [stable27] chore(deps): Downgrade nextcloud/ocp to stable27
  composer.json
  composer.lock
Labels: bug, 3. to review, dependencies

#1299 [stable27] perf(dashboard): implement widget item api v2
  js/activity-10.js
  js/activity-10.js.LICENSE.txt
  js/activity-10.js.map
  js/activity-568.js
  js/activity-568.js.LICENSE.txt
  js/activity-568.js.map
  js/activity-adminSettings.js
  js/activity-adminSettings.js.map
  js/activity-personalSettings.js
  js/activity-personalSettings.js.map
  js/activity-sidebar.js
  js/activity-sidebar.js.map
  lib/Dashboard/ActivityWidget.php
  package-lock.json
  package.json
  src/dashboard.js
  src/views/Dashboard.vue
  webpack.js
Labels: enhancement, 3. to review

#1279 [master] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies, feedback-requested

#1308 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1309 fix(db): pre- SELECT ids with a LIMIT to control the amount of rows deleted for MySQL
  lib/AppInfo/Application.php
  lib/Data.php
  psalm.xml
  tests/Controller/APIv1ControllerTest.php
  tests/DataDeleteActivitiesTest.php
  tests/DataTest.php
Labels: bug, 3. to review, backport-request

#1242 [stable24] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1325 Bump cypress to v13
  cypress/e2e/filesUtils.ts
  cypress/e2e/sidebarUtils.ts
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1323 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1335 [stable26] Create fixup.yml
  .github/workflows/fixup.yml
Labels: 3. to review

#1327 [stable26] Bump cypress to v13
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1313 [stable26] fix(db): also chunk MariaDB deletes
  lib/AppInfo/Application.php
  lib/Data.php
  psalm.xml
  tests/Controller/APIv1ControllerTest.php
  tests/DataDeleteActivitiesTest.php
  tests/DataTest.php
Labels: bug, 4. to release

#1260 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies, feedback-requested

#1336 [stable27] Re-enabled cypress tests
  .github/workflows/cypress.yml
  .github/workflows/cypress.yml.txt
  .github/workflows/fixup.yml
  cypress.config.ts
  cypress.json
  cypress/.eslintrc.js
  cypress/.eslintrc.json
  cypress/Dockerfile
  cypress/docker-compose.yml
  cypress/dockerNode.ts
  cypress/e2e/filesUtils.ts
  cypress/e2e/settings.cy.ts
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
  cypress/fixtures/example.json
  cypress/integration/activity.spec.js
  cypress/integration/settings.spec.js
  cypress/integration/sidebar.spec.js
  cypress/runLocal.sh
  cypress/server.sh
  cypress/support/commands.js
  cypress/support/commands.ts
  cypress/support/component-index.html
  cypress/support/component.ts
  cypress/support/e2e.ts
  cypress/support/index.js
  cypress/support/sidebar.js
  cypress/tsconfig.json
  package-lock.json
  package.json
  tsconfig.json
Labels: 3. to review

#1338 [stable26] Run npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#1312 [stable27] fix(db): also chunk MariaDB deletes
  lib/AppInfo/Application.php
  lib/Data.php
  psalm.xml
  tests/Controller/APIv1ControllerTest.php
  tests/DataDeleteActivitiesTest.php
  tests/DataTest.php
Labels: bug, 4. to release

#1339 [stable27] Run npm audit fix
  package-lock.json
Labels: 3. to review, dependencies

#1340 [stable25] Run npm audit fix
  package-lock.json
Labels: 3. to review, dependencies
