Repository nextcloud/activity, pull requests merged in 2024-06, with the labels that each got.

#1699 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1698 [master] Fix npm audit
  js/vendor.LICENSE.txt
Labels: 3. to review, dependencies

#1691 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1703 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1704 [master] Fix npm audit
  js/vendor.LICENSE.txt
Labels: 3. to review, dependencies

#1706 Update to Material Symbol icon style
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  img/activity-dark.svg
  img/activity.svg
  img/add-color.svg
  img/change.svg
  img/delete-color.svg
  img/notifications-dark.svg
Labels: design, 3. to review
