Repository nextcloud/activity, pull requests merged in 2024-02, with the labels that each got.

#1532 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1551 fix(DigestMail): Call parent constructor
  lib/BackgroundJob/DigestMail.php
Labels: bug, 3. to review, regression

#1554 Updating command-compile.yml workflow from template
  .github/workflows/command-compile.yml
Labels: dependencies

#1553 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1552 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1580 Fix folder creation in e2e tests
  cypress/e2e/filesUtils.ts
Labels: 3. to review, backport-request, javascript

#1565 [stable28] fix(CI): Correctly test against stable28 again
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  cypress.config.ts
  cypress/e2e/filesUtils.ts
  cypress/support/commands.ts
  cypress/tsconfig.json
  package-lock.json
  package.json
Labels: 4. to release
