Repository nextcloud/activity, pull requests merged in 2024-08, with the labels that each got.

#1744 fix(stream): Don't render avatar for federated users
  js/Activity.chunk.mjs
  js/Activity.chunk.mjs.map
  js/vendor.LICENSE.txt
  src/utils/richObjects.ts
Labels: bug, 3. to review, feature: stream

#1745 fix: split link upload activity type
  lib/Extension/Files_Sharing.php
  lib/FilesHooks.php
  tests/FilesHooksTest.php
Labels: 3. to review

#1583 [stable28] Bump nextcloud/vue from `8.6.2` to `8.8.1`
  .github/workflows/block-merge-eol.yml
  cypress/e2e/sidebar.cy.ts
  js/Activity-D_eia06P.mjs
  js/Activity-D_eia06P.mjs.map
  js/Activity-DnSi_WFC.chunk.mjs
  js/Activity-DnSi_WFC.chunk.mjs.map
  js/ActivityTab-CLqOTmH9.chunk.mjs
  js/ActivityTab-CLqOTmH9.chunk.mjs.map
  js/ActivityTab-Csi8e2H8.mjs
  js/ActivityTab-Csi8e2H8.mjs.map
  js/NcCheckboxRadioSwitch-DnnuXT1_-KVarLN0p.chunk.mjs
  js/NcCheckboxRadioSwitch-DnnuXT1_-KVarLN0p.chunk.mjs.map
  js/NcCheckboxRadioSwitch-PlgK1zWr-JoM2Xu0z.mjs
  js/NcCheckboxRadioSwitch-PlgK1zWr-JoM2Xu0z.mjs.map
  js/_commonjsHelpers-BdswosdL.chunk.mjs
  js/_commonjsHelpers-BdswosdL.chunk.mjs.map
  js/activity-adminSettings.mjs
  js/activity-adminSettings.mjs.map
  js/activity-api.mjs
  js/activity-api.mjs.map
  js/activity-app.mjs
  js/activity-app.mjs.map
  js/activity-personalSettings.mjs
  js/activity-personalSettings.mjs.map
  js/activity-sidebar.mjs
  js/activity-sidebar.mjs.map
  js/api-BqRqgFNj.mjs
  js/api-BqRqgFNj.mjs.map
  js/api-CYh3r_4s.chunk.mjs
  js/api-CYh3r_4s.chunk.mjs.map
  js/function-apply-j0ZN00j2.mjs
  js/function-apply-j0ZN00j2.mjs.map
  js/index-7GNHJcAy.chunk.mjs
  js/index-7GNHJcAy.chunk.mjs.map
  js/index-wOhlguUl.mjs
  js/index-wOhlguUl.mjs.map
  js/logger-BriTy9W0.mjs
  js/logger-BriTy9W0.mjs.map
  js/logger-D_1A6-cX.chunk.mjs
  js/logger-D_1A6-cX.chunk.mjs.map
  js/settings-store-cHmBXXGQ.mjs
  js/settings-store-cHmBXXGQ.mjs.map
  js/settings-store-gbhqFT9f.chunk.mjs
  js/settings-store-gbhqFT9f.chunk.mjs.map
  js/toast-7xJhDYMn-CygCYBy0.mjs
  js/toast-7xJhDYMn-CygCYBy0.mjs.map
  js/toast-7xJhDYMn-DLbgmRo1.chunk.mjs
  js/toast-7xJhDYMn-DLbgmRo1.chunk.mjs.map
  js/vendor.LICENSE.txt
  package-lock.json
  package.json
Labels: 3. to review, feedback-requested

#1680 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1751 chore: update workflows from templates
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1679 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1753 chore: Update PHP version to 8.1 and update dependencies
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review, technical debt, php
