Repository nextcloud/activity, pull requests merged in 2024-04, with the labels that each got.

#1629 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1634 [master] Fix npm audit
  js/index-BY5PybuZ.mjs.map
  js/logger-BVTvLOjn.mjs.map
  package-lock.json
Labels: 3. to review, dependencies

#1630 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1639 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1640 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1643 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1642 fix(activity): Improved activity exceptions
  docs/provider.md
  lib/Data.php
  lib/GroupHelper.php
  lib/NotificationGenerator.php
  lib/UserSettings.php
  tests/UserSettingsTest.php
Labels: 3. to review

#1644 fix(tests): Fix selecting the correct tagging field
  cypress/e2e/sidebarUtils.ts
Labels: bug, 3. to review, backport-request

#1612 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1650 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1649 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#1658 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1659 Update block-merge-eol workflow
  .github/workflows/block-merge-eol.yml
Labels: 4. to release

#1631 [stable29] Update nextcloud/ocp dependency
  .github/workflows/block-merge-eol.yml
  composer.lock
Labels: 3. to review, dependencies
