Repository nextcloud/activity, pull requests merged in 2024-07, with the labels that each got.

#1716 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1718 Migrate REUSE to TOML format
  .reuse/dep5
  REUSE.toml
Labels: 4. to release, technical debt

#1722 fix(dashboard): Fix missing dashboard icon
  lib/Dashboard/ActivityWidget.php
Labels: bug, 3. to review, backport-request

#1724 feat(DigestSender): Make `and X more` a link
  lib/DigestSender.php
Labels: enhancement, 3. to review

#1555 chore: update workflows from templates
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
  cypress.config.ts
  cypress/component/ComponentName.cy.ts
  cypress/support/component-index.html
  cypress/support/component.ts
Labels: 3. to review, dependencies, automated

#1723 fix(DigestSender): Do not add `and 1 more` in digest mail but simply include it
  lib/DigestSender.php
Labels: bug, 3. to review
