Repository nextcloud/activity, pull requests merged in 2024-03, with the labels that each got.

#1563 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1590 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1591 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1595 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#1601 [stable26] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1586 MailQueueHandler: Don't flood logs with useless messages
  lib/MailQueueHandler.php
Labels: backport-request

#1602 [stable28] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1592 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1600 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1603 [stable27] Fix npm audit
  cypress/e2e/sidebarUtils.ts
  package-lock.json
Labels: 3. to review, dependencies

#1611 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1613 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1620 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
