Repository nextcloud/activity, pull requests merged in 2024-01, with the labels that each got.

#1473 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1474 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1477 chore: update workflows from templates
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1476 chore: update workflows from templates
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: 3. to review, dependencies, automated

#1496 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1497 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1495 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1508 [stable27] Fix npm audit
  package-lock.json
Labels: 3. to review, dependencies

#1504 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1505 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1517 Update npm and node engines versions
  package.json
Labels: dependencies

#1514 [stable27] Fix unit tests for PHP 8.2
  .github/workflows/phpunit-mysql.yml
  tests/CurrentUserTest.php
  tests/Listener/SetUserDefaultsTest.php
  tests/Listener/UserDeletedTest.php
  tests/Mock/Request.php
Labels: 3. to review

#1519 fix: Replace deprecated function calls and private with public API
  composer.json
  lib/BackgroundJob/DigestMail.php
  lib/BackgroundJob/EmailNotification.php
  lib/BackgroundJob/RemoteActivity.php
  lib/Controller/APIv1Controller.php
  lib/Controller/RemoteActivityController.php
  lib/Data.php
  lib/MailQueueHandler.php
  tests/AppInfo/ApplicationTest.php
  tests/BackgroundJob/EmailNotificationTest.php
  tests/Controller/APIv1ControllerTest.php
  tests/psalm-baseline.xml
Labels: 3. to review, php

#1531 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1534 chore: Adjust add and delete icon colors to match server variables
  img/add-color.svg
  img/delete-color.svg
Labels: 3. to review, accessibility

#1542 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1520 fix: Migrate `post_share` hook to event listener
  lib/AppInfo/Application.php
  lib/FilesHooks.php
  lib/FilesHooksStatic.php
  lib/Listener/ShareEventListener.php
  tests/FilesHooksTest.php
Labels: bug, 3. to review

#1536 fix rss feed item guid
  templates/rss.php
  tests/Template/RssTest.php
Labels: bug, 3. to review
