Repository nextcloud/activity, pull requests merged in 2025-08, with the labels that each got.

#2093 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2092 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2096 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2097 fix(dashboard): enable rounded icons
  lib/Dashboard/ActivityWidget.php
Labels: bug, 3. to review, backport-request

#2098 perf: pass the node of shares around instead getting the path from id each time
  lib/FilesHooks.php
  psalm.xml
  tests/FilesHooksTest.php
  tests/psalm-baseline.xml
  tests/stubs/oca_files_sharing.php
Labels: 3. to review

#2107 fix: failing tests
  tests/Controller/APIv1ControllerTest.php
Labels: bug, 3. to review
