Repository nextcloud/activity, pull requests merged in 2025-03, with the labels that each got.

#1907 [master] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1906 [stable31] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: 3. to review, dependencies

#1914 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1916 fix: update workflows and remove default_enabled from info.xml
  .github/workflows/block-merge-eol.yml
  .github/workflows/block-merge-freeze.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  appinfo/info.xml
Labels: 3. to review

#1893 test: Use utils function from server and wait for requests
  cypress/e2e/filesUtils.ts
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
  cypress/tsconfig.json
Labels: 3. to review

#1925 fix: unshare from group activity user handling
  lib/FilesHooks.php
Labels: bug, 3. to review, backport-request

#1929 feat: exclude certain users from activity expiration
  lib/AppInfo/Application.php
  lib/Data.php
  tests/Controller/APIv1ControllerTest.php
  tests/DataDeleteActivitiesTest.php
  tests/DataTest.php
Labels: enhancement, 4. to release, pending documentation, php

#1927 feat: Use X-NC-Nickname as user identifier
  lib/CurrentUser.php
  tests/CurrentUserTest.php
Labels: enhancement, 3. to review, feature: api, php

#1931 fix: disable loading when there are no more activities to load
  js/activity-app.mjs
  js/activity-app.mjs.map
  src/views/ActivityAppFeed.vue
Labels: bug, 3. to review, backport-request

#1943 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1905 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1944 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1947 fix(settings): ensure we handle file_created, file_deleted and file_restored as file_changed
  lib/UserSettings.php
Labels: bug, 3. to review, high, backport-request
