Repository nextcloud/activity, pull requests merged in 2025-05, with the labels that each got.

#2007 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1817 [stable30] chore(dev-deps): Bump nextcloud/ocp package
  composer.json
  composer.lock
  vendor-bin/cs-fixer/composer.json
  vendor-bin/cs-fixer/composer.lock
Labels: 3. to review

#2013 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2014 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2020 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2022 chore(tests): Cleanup bootstrap.php to be forward-compatible
  tests/bootstrap.php
Labels: 3. to review

#2030 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2032 [stable31] chore: update workflows
  .github/workflows/command-compile.yml
  .github/workflows/cypress.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node-test.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mariadb.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
Labels: 3. to review

#2023 test(cypress): Enable test isolation
  cypress.config.ts
  cypress/e2e/settings.cy.ts
  cypress/e2e/sidebar.cy.ts
  cypress/e2e/sidebarUtils.ts
Labels: 3. to review, backport-request

#2012 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
