Repository nextcloud/activity, pull requests merged in 2025-04, with the labels that each got.

#1959 Revert "fix: disable loading when there are no more activities to load"
  js/activity-app.mjs
  js/activity-app.mjs.map
  src/views/ActivityAppFeed.vue
Labels: bug, 3. to review, feature: stream

#1958 Revert "fix: disable loading when there are no more activities to load"
  js/activity-app.mjs
  js/activity-app.mjs.map
  src/views/ActivityAppFeed.vue
Labels: 3. to review, feature: stream

#1954 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1975 fix: Improving logging of invalid parameters for activity subject and…
  lib/GroupHelper.php
Labels: bug, 3. to review, backport-request, feature: api

#1710 [stable29] Fix npm audit
  cypress.config.ts
  js/Activity-BmFoI2Lq.chunk.mjs
  js/Activity-BmFoI2Lq.chunk.mjs.map
  js/Activity-CuRn5nA-.mjs
  js/Activity-CuRn5nA-.mjs.map
  js/ActivityTab-B5_Oldhx.chunk.mjs
  js/ActivityTab-B5_Oldhx.chunk.mjs.map
  js/ActivityTab-DESrkXIy.mjs
  js/ActivityTab-DESrkXIy.mjs.map
  js/NcCheckboxRadioSwitch-BaMf0PDd-q9229gvE.chunk.mjs
  js/NcCheckboxRadioSwitch-BaMf0PDd-q9229gvE.chunk.mjs.map
  js/NcCheckboxRadioSwitch-hel9-sAH-B2kF2zXo.mjs
  js/NcCheckboxRadioSwitch-hel9-sAH-B2kF2zXo.mjs.map
  js/NcNoteCard-C6xb7vi0-D-XOuXI_.chunk.mjs
  js/NcNoteCard-C6xb7vi0-D-XOuXI_.chunk.mjs.map
  js/_commonjsHelpers-BhChsaSm.chunk.mjs
  js/_commonjsHelpers-BhChsaSm.chunk.mjs.map
  js/activity-adminSettings.mjs
  js/activity-adminSettings.mjs.map
  js/activity-api.mjs
  js/activity-api.mjs.map
  js/activity-app.mjs
  js/activity-app.mjs.map
  js/activity-personalSettings.mjs
  js/activity-personalSettings.mjs.map
  js/activity-sidebar.mjs
  js/activity-sidebar.mjs.map
  js/api-BKkaSPgn.mjs
  js/api-BKkaSPgn.mjs.map
  js/api-DVEfoW9x.chunk.mjs
  js/api-DVEfoW9x.chunk.mjs.map
  js/index-BTKMp2fI.chunk.mjs
  js/index-BTKMp2fI.chunk.mjs.map
  js/index-CcIXDn2h.mjs
  js/index-CcIXDn2h.mjs.map
  js/index-DCIakzaT.chunk.mjs
  js/index-DCIakzaT.chunk.mjs.map
  js/index-LkGPsUV3.mjs
  js/index-LkGPsUV3.mjs.map
  js/logger--0ns4cKc.chunk.mjs
  js/logger--0ns4cKc.chunk.mjs.map
  js/logger-BVTvLOjn.mjs
  js/logger-BVTvLOjn.mjs.map
  js/preload-helper-CfzTJz-5.chunk.mjs
  js/preload-helper-CfzTJz-5.chunk.mjs.map
  js/settings-store-arhbQM9F.chunk.mjs
  js/settings-store-arhbQM9F.chunk.mjs.map
  js/settings-store-hQXILuzh.mjs
  js/settings-store-hQXILuzh.mjs.map
  js/toast-7xJhDYMn-4LEThH4X.mjs
  js/toast-7xJhDYMn-4LEThH4X.mjs.map
  js/vendor.LICENSE.txt
  package-lock.json
  package.json
Labels: 3. to review, dependencies

#1976 fix: don't setup the filesystem to check if a user is blocked by ACLs
  lib/FilesHooks.php
Labels: 3. to review

#1989 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#2004 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies

#1953 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: 3. to review, dependencies
